---
title: 2020 ECAASU Conference - Building Bridges
tagline: "Building Bridges"
url: "http://ecaasuconf2020.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

register_link: "https://ecaasuinc.wufoo.com/forms/zjcnyd11t538ea/"
facebook_link: "https://www.facebook.com/ECAASUConference/"
ideathon_register_link: "https://docs.google.com/forms/d/e/1FAIpQLScFE7nx_qoLaeE9QZIdsLDvEhUSjAZI1OkZY7fAnrNbKHYYKg/viewform?usp=sf_link"
turbovote_link: "https://ecaasu.turbovote.org"

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]